---
services:
  db:
    image: mariadb:11.4.7
    restart: always
    user: 1001:1001
    environment:
      MARIADB_DATABASE: "webtrees"
      MARIADB_USER: "webtrees"
      MARIADB_ROOT_PASSWORD: "badrootpassword"
      MARIADB_PASSWORD: "baddbpassword"
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    image: webtrees:2.2.1
    restart: always
    user: 16847:16847
    depends_on:
      - db
    environment:
      PRETTY_URLS: "false"
      LANG: "en-US"
      BASE_URL: "http://127.0.0.1:8080"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "baddbpassword"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER: "username"
      WT_NAME: "Full Name"
      WT_PASS: "badwtpassword"
      WT_EMAIL: "me@example.com"
    ports:
      - 8080:8080
    volumes:
      - ./app_data:/var/www/webtrees/data/
